require(shiny)
require(shinydashboard)
require(shinyjs)
require(leaflet)
require(ggvis)
library(plyr)
require(dplyr)
library(RColorBrewer)
require(raster)
require(gstat)
require(rgdal)
require(Cairo)
library(sp)
library(htmltools)


FULL.val <-read.csv("data/shiny climatesd.csv")
class(FULL.val)  
na.omit(FULL.val)
colnames(FULL.val) <-c("lng", "lat", "id"="id","name"="name",	"country"="country", "CS_number"="CS_number", "group"="group","CO_Spring" = "CO Spring (ppbv)" ,"CO_Summer"= "CO Summer (ppbv)", "NO2_Spring"= "NO2 Spring (billion molecules/mm2)",	"NO2_Summer"= "NO2 Summer (billion molecules/mm2)",	"O3_Spring"="O3 Spring (Dobson Units)",	"O3_Summer"= "O3 Summer (Dobson Units)",
                       "SIB3_carbon_flux_spring"="SIB3 carbon flux spring (mol/m2/seg)",	"SIB3_carbon_flux_summer"="SIB3 carbon flux summer (mol/m2/seg)",	"UV_index_spring"="UV index spring",	"UV_index_summer"="UV index summer",	"Solar_insolation_spring"= "Solar insolation spring (W/m2)",	"Solar_insolation_summer"= "Solar insolation summer (W/m2)",	"Net_radiation_spring" ="Net radiation spring (W/m2)",	"Net_radiation_summer"="Net radiation summer (W/m2)",	"WATER_EQUIVALENT_ANOMALY_spring" = "Water eq. anomaly spring (cm)",	"WATER_EQUIVALENT_ANOMALY_summer"= "Water eq. anomaly summer (cm)",	"Rainfall_spring"= "Rainfall spring (mm)",	"Rainfall_summer"= "Rainfall summer (mm)",	"Precipitable_water_spring"= "Precipitable water spring (cm)",	"Precipitable_water_summer"= "Precipitable water summer (cm)",	"LTemp_day_spring"="LTemp day spring (°C)",	"LTemp_day_summer"="LTemp day summer (°C)",	"Ltemp__night_spring"="LTemp night spring (°C)",	"Ltemp__night_summer"="LTemp night summer (°C)", 
                       "NDVI_Spring"="NDVI Spring",	"NDVI_Summer"="NDVI Summer",	"LAI_Spring"="LAI Spring (m2/m2)",	"LAI_Summer"="LAI Summer (m2/m2)",	"PET" ="PET (mm/yr)",	"ET"="ET (mm/yr)",	"LE"="LE (W/m2)",	"Aridity_index"="Aridity index",	"Climatic_water_deficit"="Climatic water deficit (mm/yr)",	"Number_of_dry_months"="Number of dry months (days)",	"GPP_Spring"="GPP Spring (gC/m2/day)",	"GPP_Summer"="GPP Summer (gC/m2/day)",	"NPP_Spring"="NPP Spring (gC/m2/day)",	"NPP_Summer"="NPP Summer (gC/m2/day)",	"Topography"="USGS:GTOPO30 Topography (m)",	"SRTM elevation"= "NASA: SRTM elevation (m)",	"SMT_Spring"="AVHRR Smoothed Brightness Temperature summer",	"SMT_Summer"="AVHRR Smoothed Brightness Temperature spring",	"SMN_Spring"="AVHRR Smoothed NDVI spring",	"SMN_Summer"="AVHRR Smoothed NDVI summer",	"TCI_Spring"="AVHRR Temperature Condition Index spring",	"TCI_Summer"="AVHRR Temperature Condition Index summer",	"VCI_Spring"="AVHRR Vegetation Condition Index spring",	"VCI_Summer"="AVHRR Vegetation Condition Index summer",	"VHI_Spring"="AVHRR Vegetation Health Index spring",	"VHI_Summer"="AVHRR Vegetation Health Index summer",	"CO2_Emissions"= "ISLSCP II CO2 EMISSIONS (C/cm2/sec)",	"WB_PVOUT"= "WB PVOUT (kWh/kWp)",	"WB_GHI"= "WB GHI (kWh/m2)",	"WB_DIF"= "WB DIF (kWh/m2)",	"WB_GTI"=	"WB GTI (kWh/m2)",	"WB_OPTA"= "WB OPTA (degrees)",	"WB_DNI"="WB DNI (kWh/m2)",	"WB_TEMP"= "WB TEMP (°C)",	"WC_ELE"="WB ELE (m)",	"GPCC_Spring"="GPCC Spring (mm)",	"GPCC_Summer"="GPCC Summer (mm)",
                       "WC2_Tmin_spring"="WC2 Tmin spring (°C)",	"WC2_Tmin_summer"="WC2 Tmin summer (°C)",	"WC2_Tmax_spring"="WC2 Tmax spring (°C)",	"WC2_Tmax_summer"="WC2 Tmax summer (°C)",	"WC2_Pre_spring"="WC2 Pre spring (mm)",	"WC2_Pre_summer"="WC2 Pre summer (mm)",	"WC2_Solar_radiation_spring"="WC2 Solar radiation spring (kJ m-2 day-1)",	"WC2_Solar_radiation_summer"="WC2 Solar radiation summer (kJ m-2 day-1)",	"WC2_Average_temperature_spring"="WC2 Average temperature spring (°C)",	"WC2_Average_temperature_summer"="WC2 Average temperature summer (°C)",	"WC2_Water_vapor_pressure_spring"="WC2 Water vapor pressure spring (kPa)",	"WC2_Water_vapor_pressure_summer"="WC2 Water vapor pressure summer (kPa)",	"WC2_BIO1"= "WC BIO1 (°C)",	"WC2_BIO2"="WC2_BIO2 (°C)",	"WC2_BIO3"="WC2_BIO3 (°C)",	"WC2_BIO4"="WC2 BIO4 (°C)",	"WC2_BIO5"="WC2 BIO5 (°C)",	"WC2_BIO6"="WC2 BIO6 (°C)",	"WC2_BIO7"="WC2 BIO7 (°C)",	"WC2_BIO8"="WC2 BIO8 (°C)",	"WC2_BIO9"="WC2 BIO9 (°C)",	"WC2_BIO10"="WC2 BIO10 (°C)",	"WC2_BIO11"="WC2 BIO11 (°C)",	"WC2_BIO12"="WC2 BIO12 (mm)",	"WC2_BIO13"="WC2 BIO13 (mm)",	"WC2_BIO14"="WC2 BIO14 (mm)",	"WC2_BIO15"="WC2 BIO15 (mm)",	"WC2_BIO16"= "WC2 BIO16 (mm)",	"WC2_BIO17"= "WC2 BIO17 (mm)",	"WC2_BIO18"="WC2 BIO18 (mm)",	"WC2_BIO19"="WC2 BIO19 (mm)",
                       "CHELSA_Tmin_Spring"="CHELSA Tmin Spring (°C)",	"CHELSA_Tmin_spring"="CHELSA Tmin spring (°C)",	"CHELSA_Tmax_spring"="CHELSA Tmax spring (°C)",	"CHELSA_Tmax_summer"="CHELSA Tmax summer (°C)",	"CHELSA_Tmean_spring"="CHELSA Tmean spring (°C)",	"CHELSA_Tmean_summer"="CHELSA Tmean summer (°C)",	"CHELSA_Interann_Temp"="CHELSA Interann_Temp (°C)",	"CHELSA_Pre_spring"="CHELSA Pre spring (mm)",	"CHELSA_Pre_summer"="CHELSA Pre summer (mm)",	"CHELSA_Interann_pre"="CHELSA Interann pre (mm)",	"CHELSA_BIO1"="CHELSA BIO1 (°C) ",	"CHELSA_BIO2"="CHELSA BIO2 (°C)",	"CHELSA_BIO3"= "CHELSA BIO3 (°C)",	"CHELSA_BIO4"="CHELSA BIO4 (°C)",	"CHELSA_BIO5"="CHELSA BIO5 (°C)",	"CHELSA_BIO6"="CHELSA BIO6 (°C)", "CHELSA_BIO7"="CHELSA BIO7 (°C)",	"CHELSA_BIO8"="CHELSA BIO8 (°C)",	"CHELSA_BIO9"="CHELSA BIO9 (°C)",	"CHELSA_BIO10"="CHELSA BIO10 (°C)",	"CHELSA_BIO11"="CHELSA BIO11 (°C)",	"CHELSA_BIO12"="CHELSA BIO12 (mm)",	"CHELSA_BIO13"="CHELSA BIO13 (mm)",	"CHELSA_BIO14"="CHELSA BIO14 (mm)",	"CHELSA_BIO15"="CHELSA BIO15 (mm)",	"CHELSA_BIO16"="CHELSA BIO16 (mm)",	"CHELSA_BIO17"="CHELSA BIO17 (mm)",	"CHELSA_BIO18"="CHELSA BIO18 (mm)",	"CHELSA_BIO19"="CHELSA BIO19 (mm)",
                       "CRU_Cld_spring" ="CRU Cld spring (%)",	"CRU_Cld_summer"="CRU Cld summer (%)",	"CRU_Dtr_spring"="CRU Dtr spring (°C)",	"CRU_Dtr_summer"="CRU Dtr summer (°C)",	"CRU_Frs_spring"="CRU Frs spring (days)",	"CRU_Frs_summer"="CRU Frs summer (days)",	"CRU_Pre_spring"="CRU Pre spring (mm)",	"CRU_Pre_summer"="CRU Pre summer (mm)",	"CRU_Tmp_spring"="CRU Tmp spring (°C)",	"CRU_Tmp_summer"="CRU Tmp summer (°C)",	"CRU_Tmn_spring"="CRU Tmn spring (°C)",	"CRU_Tmn_summer"="CRU Tmn summer (°C)",	"CRU_Tmx_spring"="CRU Tmx spring (°C)",	"CRU_Tmx_summer"="CRU Tmx summer (°C)",	"CRU_Vap_spring"="CRU Vap spring (hPa)",	"CRUVap_summer"="CRUVap_summer (hPa)",	"CRU_Wet_spring"="CRU Wet spring (days)",	"CRU_Wet_summer"="CRU Wet summer (days)",	"CRU_PET_Spring"="CRU PET Spring (mm)",	"CRU_PET_Summer"="CRU PET Summer (mm)",	"Bedrock_topography"="Bedrock topography (meters)",
                       "dNPPdP"="dNPPdP (g/m2/mm)",	"dNPPdT"="dNPPdT (g/m2/ºC)",	"CRU_NPP"="CRU NPP (g/m2)",	"NPP_based_on_GPCP"="NPP based on GPCP (g/m2)",	"NPP_based_on_GPCP_VASClimO"="NPP based on GPCP VASClimO  (g/m2)",	"GPCC_VASClimO_Precipitation"= "GPCC VASClimO Precipitation (mm)",	"CRU_Precipitation"="CRU Precipitation (mm)",	"CRU_Temperature"="CRU_Temperature (ºC)",	"Griesser_Precip_GPCC"="Griesser_Precip_GPCC (mm)",	"GPCC_Fulldata_Precipitation"="GPCC Fulldata Precipitation",	"Aridity_index_of_De_Martonne_GPCC_Fulldata"="Aridity index of De Martonne GPCC Fulldata",	"Aridity_index_of_De_Martonne_GPCC_VASClimO"="Aridity index of De Martonne GPCC VASClimO",	"Aridity_index_of_De_Martonne_CRU"="Aridity index of De Martonne CRU",	"HWSD_Topsoil_ref_bulk_dens"="HWSD Topsoil ref bulk dens (kg/dm3)",	"HWSD_Topsoil_clay_fraction"="HWSD Topsoil clay fraction (%)",	"HWSD_Topsoil_gravel_content"="HWSD Topsoil gravel content (%)",	"HWSD_Topsoil_silt_fraction"="HWSD Topsoil silt fraction (%)",	"HWSD_Topsoil_sand_fraction"="HWSD Topsoil sand fraction (%)",	"HWSD_Topsoil_organic_carbon"="HWSD Topsoil organic carbon (%)",	"HWSD_Topsoil_pH"="HWSD Topsoil pH (-log(H+))",	"HWSD_Subsoil_ref_bulk_dens"="HWSD Subsoil ref bulk dens (kg/dm3)",	"HWSD_Subsoil_clay_fraction"= "HWSD Subsoil clay fraction (%)",	"HWSD_Subsoil_gravel_content"="HWSD Subsoil gravel content (%)",	"HWSD_Subsoil_silt_fraction"="HWSD Subsoil silt fraction (%)",	"HWSD_Subsoil_sand_fraction"="HWSD Subsoil sand fraction (%)",	"HWSD_Subsoil_organic_carbon"="HWSD Subsoil organic carbon (%)",	"HWSD_Subsoil_pH"="HWSD Subsoil pH (-log(H+))",	"HWSD_Spatially_dominan_major_soil_group_FAO"= "HWSD Spatially dominan major soil group FAO",	"ISRIC_WISE_SoilCarbonate_Carbon_Dens"="ISRIC WISE SoilCarbonate Carbon Dens (kg C/m)",	"ISRIC_WISE_Soil_Org_Carbon_Dens"= "ISRIC WISE Soil Org Carbon Dens (kg C/m)",	"ISRIC_WISE_Soil_pH"="ISRIC WISE Soil pH (log(H+))",	"ISRIC_WISE_Total_AvailWater_cap"="ISRIC WISE Total AvailWater cap (mm)", 
                       "SoilGrids_BDRICM"="SoilGrids absolute depth to bedrock (cm)",	"SoilGrids_BLDFIE"= "SoilGrids bulk density (kg/m3)",	"SoilGrids_CECSOL"="SoilGrids cation exchange capacity of soil (meq/100 g)",	"SoilGrids_CLYPPT"="SoilGrids clay content (%)",	"SoilGrids_CRFVOL"="SoilGrids course fragments volumetric (%)",	"SoilGrids_OCSTHA"="SoilGrids soil organic carbon stock per ha (kg/m3)",	"SoilGrids_ORCDRC"="SoilGrids soil organic carbon content (‰)",	"SoilGrids_PHIHOX"="SoilGrids soil pH H2O (log(H+))",	"SoilGrids_PHIKCL"="SoilGrids soil pH KCL (log(H+))",	"SoilGrids_SLTPPT"="SoilGrids silt content (%)",	"SoilGrids_SNDPPT"= "SoilGrids sand content (%)",	"SoilGrids_TAXNWRB"="SoilGrids observed taxonomic class (WRB system)",	"SoilGrids_TAXOUSDA"="SoilGrids observed taxonomic class(USDA system)",	"GAEZ_Nutrient_availability" ="GAEZ Nutrient availability",	"GAEZ_Nutrient_retention_capacity"="GAEZ Nutrient retention capacity",	"GAEZ_Rooting_conditions"="GAEZ Rooting conditions",	"GAEZ_Oxygen_availability_to_roots"="GAEZ Oxygen availability to roots",	"GAEZ_Excess_salts"="GAEZ Excess salts",	"GAEZ_Toxicity"="GAEZ Toxicity",	"Plant_Extractable_Water_Capacity_of_Soil"="Plant extractable water capacity of Soil (cm/cm)",	"IGBP_DIS_Soil_pH"="IGBP DIS Soil pH (-log(H+))",	"Suitability_for_Agriculture"="Suitability for Agriculture (index)",	"Growing_degree_days"="Growing degree (days)",	"Distance_to_the_coast"="Distance to the coast (Km)",	"Bailey_ecoregions"="Bailey ecoregions",	"Land_cover_2000"="Land cover 2000",	"UMD_Land_cover_classification"="UMD Land cover classification",	"Distribution_of_Cultivation_Intensity"="Distribution of Cultivation Intensity",	"Koppen_Geiger"="Koppen Geiger",	"Geological_ages"= "Geological ages",	"Soil_types"="Soil types (Zobler)")

# a data.frame

FULL <- SpatialPointsDataFrame(FULL.val[,c("lng", "lat")], FULL.val[,1:212])

#########

descriptiondataset <-read.csv("data/datadescription.csv")


datasets <- list(
  'FULL'=  FULL,
  'descriptiondataset'
  
)

baselayers <- list(
  'FULL'='Esri.WorldImagery'
)

